### ISSUE TITLE
Post is not an initialized or populated object.

### ISSUE THREAD

**Issue by jarrodnorwell** [jeed2424/IG_Schedule#1]
@antique_codes from Reddit, you haven't created a new Post object using the necessary data.

Edit: Looks like you need to do Post(init: params)?

https://github.com/jeed2424/IG_Schedule/blob/77512fe02421515c1de1be11235b578a799edba6/IG%20Schedule/ScheduleAndPostVC.swift#L843

**Comment by jeed2424** [comment]
Yes, I ended up working on it yesterday. I created a new Story object instead because of the confusion/distinction between the two (post and story). Now everything works except I’d like to save the image to camera roll when the user taps on the notification but nothing seems to work… I’ll update the repo accordingly soon enough!
